const REQUEST_SERVICE_DETAIL = '[REQUEST_SERVICE] REQUEST_SERVICE_DETAIL';
const REQUEST_SERVICE_FORM = '[REQUEST_SERVICE] REQUEST_SERVICE_FORM';

const REQUEST_SERVICE_REQUEST = '[REQUEST_SERVICE] REQUEST_SERVICE_REQUEST';
const REQUEST_SERVICE_SUCCESS = '[REQUEST_SERVICE] REQUEST_SERVICE_SUCCESS';
const REQUEST_SERVICE_FAILURE = '[REQUEST_SERVICE] REQUEST_SERVICE_FAILURE';
