const BANNER_LIST_REQUEST = '[BANNER_LIST] BANNER_LIST_REQUEST';
const BANNER_LIST_SUCCESS = '[BANNER_LIST] BANNER_LIST_SUCCESS';
const BANNER_LIST_FAILURE = '[BANNER_LIST] BANNER_LIST_FAILURE';

const REQUEST_SERVICE_LIST_REQUEST =
    '[REQUEST_SERVICE_LIST] REQUEST_SERVICE_LIST_REQUEST';
const REQUEST_SERVICE_LIST_SUCCESS =
    '[REQUEST_SERVICE_LIST] REQUEST_SERVICE_LIST_SUCCESS';
const REQUEST_SERVICE_LIST_FAILURE =
    '[REQUEST_SERVICE_LIST] REQUEST_SERVICE_LIST_FAILURE';

const SERVICES_LIST_REQUEST = '[SERVICES_LIST] SERVICES_LIST_REQUEST';
const SERVICES_LIST_SUCCESS = '[SERVICES_LIST] SERVICES_LIST_SUCCESS';
const SERVICES_LIST_FAILURE = '[SERVICES_LIST] SERVICES_LIST_FAILURE';
