const LOGIN_REQUEST = '[LOGIN_SUCCESS] LOGIN_REQUEST';
const LOGIN_SUCCESS = '[LOGIN_SUCCESS] LOGIN_SUCCESS';
const LOGIN_FAILURE = '[LOGIN_SUCCESS] LOGIN_FAILURE';

const UPDATE_SESSION_REQUEST = '[UPDATE_SESSION] UPDATE_SESSION_REQUEST';
const UPDATE_SESSION_SUCCESS = '[UPDATE_SESSION] UPDATE_SESSION_SUCCESS';
const UPDATE_SESSION_FAILURE = '[UPDATE_SESSION] UPDATE_SESSION_FAILURE';
