// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE8enfp9K1D2IALQ5zrou2739xxYCufMw',
    appId: '1:821113689558:web:09e9f24a391a42e569c077',
    messagingSenderId: '821113689558',
    projectId: 'mnsolutions-9af67',
    authDomain: 'mnsolutions-9af67.firebaseapp.com',
    storageBucket: 'mnsolutions-9af67.appspot.com',
    measurementId: 'G-118Q40ZZYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW_1NtdXZZGBhLgoznjqBPnRxV5l9cotM',
    appId: '1:821113689558:android:8f24df49ab32ff9569c077',
    messagingSenderId: '821113689558',
    projectId: 'mnsolutions-9af67',
    storageBucket: 'mnsolutions-9af67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASa0k_8Lr0iX1qfccKlOyRVQJOvI_3woM',
    appId: '1:821113689558:ios:7468fc9649d86e8769c077',
    messagingSenderId: '821113689558',
    projectId: 'mnsolutions-9af67',
    storageBucket: 'mnsolutions-9af67.appspot.com',
    iosClientId:
        '821113689558-s9hv41qor6a0sc2k1mr5sg81foskgj29.apps.googleusercontent.com',
    iosBundleId: 'com.mnsolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASa0k_8Lr0iX1qfccKlOyRVQJOvI_3woM',
    appId: '1:821113689558:ios:7468fc9649d86e8769c077',
    messagingSenderId: '821113689558',
    projectId: 'mnsolutions-9af67',
    storageBucket: 'mnsolutions-9af67.appspot.com',
    iosClientId:
        '821113689558-s9hv41qor6a0sc2k1mr5sg81foskgj29.apps.googleusercontent.com',
    iosBundleId: 'com.mnsolutions',
  );
}
