const ADDRESS_FORM = '[ADDRESS] ADDRESS_FORM';

const SAVE_ADDRESS_REQUEST = '[SAVE_ADDRESS] SAVE_ADDRESS_REQUEST';
const SAVE_ADDRESS_SUCCESS = '[SAVE_ADDRESS] SAVE_ADDRESS_SUCCESS';
const SAVE_ADDRESS_FAILURE = '[SAVE_ADDRESS] SAVE_ADDRESS_FAILURE';
