const SUBSCRIPTION_CARD_FORM = '[SUBSCRIPTION] SUBSCRIPTION_CARD_FORM';
const SUBSCRIPTION_PLAN_FORM = '[SUBSCRIPTION] SUBSCRIPTION_PLAN_FORM';

const SUBSCRIPTION_PLANS_REQUEST = '[SUBSCRIPTION] SUBSCRIPTION_PLANS_REQUEST';
const SUBSCRIPTION_PLANS_SUCCESS = '[SUBSCRIPTION] SUBSCRIPTION_PLANS_SUCCESS';
const SUBSCRIPTION_PLANS_FAILURE = '[SUBSCRIPTION] SUBSCRIPTION_PLANS_FAILIRE';

const SUBSCRIPTION_REQUEST = '[SUBSCRIPTION] SUBSCRIPTION_REQUEST_LOADING';
const SUBSCRIPTION_SUCCESS = '[SUBSCRIPTION] SUBSCRIPTION_REQUEST_SUCCESS';
const SUBSCRIPTION_FAILURE = '[SUBSCRIPTION] SUBSCRIPTION_REQUEST_FAILURE';
